test-project:
  stage: test
  script:
    - cd ecommerce-backend
    - bundle install
  only:
    - project
deploy-project:
  stage: deploy
  script:
    - rsync -arv --delete  --exclude="*.sqlite3" ./ecommerce-backend /
    - rsync -arv --delete  --exclude="*.sqlite3" ./ecommerce-frontend /
    - cd /ecommerce-frontend
    - npm install
    - npm run dev
    - cd /ecommerce-backend
    - bundle install
    - rails db:migrate
    - rails db:seed
    - sv restart project
  only:
  - project
