test-project:
  stage: test
  script:
    - cd ecommerce-backend
    - bundle install
  only:
    - project
deploy-project:
  stage: deploy
  script:
    - rsync -arv --delete  --exclude="*.sqlite3" ./ecommerce-backend /
    - cd /ecommerce-backend
    - bundle install
    - rails db:migrate
    - rails db:seed
    - sv restart project
  only:
  - project
