test-project:
  stage: test
  script:
    - cd project
    - bundle install
    - rails db:migrate RAILS_ENV=test
    - PARALLEL_WORKERS=1 rails test
  only:
    - project
deploy-project:
  stage: deploy
  script:
    - rsync -arv --delete  --exclude="*.sqlite3" ./project /
    - cd /ecommerce-frontend
    - npm install
    - npm run dev
    - cd /ecommerce-backend
    - bundle install
    - rails db:migrate
    - rails db:seed
    - sv restart project
  only:
  - project
